name: Snapshot NHSN data and upload to S3

on:
  schedule:
    - cron: "45 12 * * 3" # every Wednesday at 5:45PM UTC == 12:45PM EST
  workflow_dispatch:

env:
  # Reich lab AWS account number
  AWS_ACCOUNT: 312560106906

jobs:
  snapshot-nhsn-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R 📊
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4.1
          install-r: true
          use-public-rspm: true
          extra-repositories: 'https://hubverse-org.r-universe.dev'

      - name: install R packages
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('Chicago/RSocrata@v1.7.11')"
      
      - name: Snapshot NHSN data
        run: Rscript -e "nhsn_data <- RSocrata::read.socrata('https://data.cdc.gov/resource/mpgq-jmmr.csv'); 
                         write.csv(nhsn_data, paste0('nhsn-', Sys.Date(), '.csv'))"
      
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          rclone version
      
      - name: Copy to cloud storage
        # copy the created file to S3
        run: |
          rclone copy ./data/ ":s3,provider=AWS,env_auth:infectious-disease-data/data-raw/influenza-nhsn" \
            --checksum --verbose --stats-one-line --config=/dev/null
        shell: bash
